# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts

version: 2.1

orbs:
  # Note: We are using the latest version of hello-build, whereas module B uses an older one
  module-a-hello-build: circleci/hello-build@0.0.14

jobs:
  module-a-build:
    docker:
      - image: alpine
    steps:
      - common-say-hello:
          to: A
      - run: echo 'Hello world from module A! :3'

workflows:
  module-a-workflow:
    jobs:
      - common-pre
      - module-a-build:
          requires:
            - common-pre
      - module-a-hello-build/hello-build:
          requires:
            - common-pre
