# Config dedicated for php module
# All the resources must be prefixed with `php-` to avoid conflicts

version: 2.1

orbs:
  # Note: We are using the latest version of hello-build, whereas module B uses an older one
  php-hello-build: circleci/hello-build@0.0.14

jobs:
  php-build:
    docker:
      - image: alpine
    steps:
      - common-say-hello:
          to: A
      - run: echo 'Hello world from module A! :3'

workflows:
  php-workflow:
    jobs:
      - common-pre
      - php-build:
          requires:
            - common-pre
      - php-hello-build/hello-build:
          requires:
            - common-pre
