# Config dedicated for e2e module
# All the resources must be prefixed with `e2e-` to avoid conflicts

version: 2.1

orbs:
  e2e-hello-build: circleci/hello-build@0.0.14

jobs:
  e2e-build:
    docker:
      - image: alpine
    steps:
      - common-say-hello:
          to: C
      - run: echo 'Hello world from module C! :3'

workflows:
  e2e-workflow:
    jobs:
      - common-pre
      - e2e-build:
          requires:
            - common-pre
      - e2e-hello-build/hello-build:
          requires:
            - common-pre
